display_name = "Tr4sh Rebuffed S Movesets"
authors = "JABrules, Meli Satana, Aka7"
version = "1.13.0"
description = """
The necessary parameter and moveset edits for
Tr4sh Rebuffed S to function as intended.
"""
category = "Misc"