display_name = "Tr4sh Rebuffed Movesets"
authors = "JABrules, Meli Satana, Aka7"
version = "1.18.0"
description = """
The necessary parameter and moveset edits for
Tr4sh Rebuffed to function as intended.
"""
category = "Misc"