display_name = "Tr4sh Rebuffed Moveset Data"
authors = "JABrules, Meli Satana, Aka7"
version = "1.37.0"
description = """
The necessary parameter and moveset edits for
Tr4sh Rebuffed to function as intended.
"""
category = "Misc"